version: '3'
services:

  worker-master:
    hostname: worker
    command: "poetry run flask run -p5000 -h0.0.0.0 --reload"
    build:
      context: .
      dockerfile: ./docker/worker.Dockerfile
    volumes:
    - .:/code
    links:
    - redis
    - rabbitmq

  web:
    hostname: web
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    links:
    - rabbitmq
    - worker-master

  fiber:
    hostname: fiber
    build:
      context: .
      dockerfile: ./docker/fiber.Dockerfile
    links:
    - rabbitmq
    environment:
      WEBSOCKET_HOST: 0.0.0.0
      WEBSOCKET_PORT: 8080
    volumes:
    - .:/code
    ports:
    - "8080:8080"

  redis:
    hostname: redis 
    image: redis

  rabbitmq:
    ports:
    - "15672:15672"
    hostname: rabbitmq
    image: rabbitmq:3-management
